version: '3.9'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.prod
    env_file:
      - ./frontend/.env.production
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - '5004:5004'
    env_file:
      - ./backend/.env

